"""add quantity column to product

Revision ID: 3b98710662fc
Revises: 47568d169753
Create Date: 2026-09-23 22:56:09.829044

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3b98710662fc"
down_revision: Union[str, Sequence[str], None] = "47568d169753"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "quantity",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    # ### end Alembic commands ###
    op.alter_column(
        "products",
        "quantity",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "quantity")
    # ### end Alembic commands ###
