"""add query indexes

Revision ID: d2869c70b12e
Revises: c38a4395677a
Create Date: 2026-10-09 01:08:08.646349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2869c70b12e'
down_revision: Union[str, Sequence[str], None] = 'c38a4395677a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_orders_user_created_id', 'orders', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_orders_user_created_id', table_name='orders')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    # ### end Alembic commands ###
