"""add hashed password to users

Revision ID: ea47865917c9
Revises: d1dc9bb1f661
Create Date: 2026-09-23 00:55:26.531668

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ea47865917c9"
down_revision: Union[str, Sequence[str], None] = "d1dc9bb1f661"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=False,
            server_default="",
        ),
    )

    op.alter_column(
        "users",
        "hashed_password",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
